### ISSUE TITLE
how to install...like a brief doc u can provide for new devs

### ISSUE THREAD

**Issue by skub007** [KoBeWi/Godot-Instance-Dock#10]
as the title says...sry

**Comment by KoBeWi** [comment]
1. Download the plugin from AssetLib
2. In Godot, go to Project -> Project Settings -> Plugins
3. Enable Instance Dock

Alternatively:
1. Download ZIP from GitHub
2. Unzip it in your project (make sure the addon is in `addons/InstanceDock` directory)
3. Enable in project settings

EDIT:
It's in the official documentation and process is the same for most addons: https://docs.godotengine.org/en/stable/tutorials/plugins/editor/installing_plugins.html
