### ISSUE TITLE
Use HFlowContainer over GridMap in slot container

### ISSUE THREAD

**Issue by Mickeon** [KoBeWi/Godot-Instance-Dock#2]
I've recently taken a look at this pretty neat addon. I was taken aback by how wide it expanded the side panel.

The title is pretty self explanatory. A few tweaks on the addon have it work as I expected. It was not easily feasible back when the addon was first released, but since 3.5, a **HFlowContainer** could theoretically be supported.

![image](https://user-images.githubusercontent.com/66727710/226213690-7aa893de-0aa1-4f56-b7f5-c7c01816e616.png)

**Comment by KoBeWi** [comment]
It already uses HFlowContainer.
https://github.com/KoBeWi/Godot-Instance-Dock/blob/50ba668b7d2dfc2982e0a6271d487c0a5f1a4e4e/addons/InstanceDock/InstanceDock.tscn#L40
Not in the 3.x version tho, as I stopped updating it.

**Comment by KoBeWi** [comment]
Closing per above comment.
