### ISSUE TITLE
Configurable instances

### ISSUE THREAD

**Issue by brian-holsters** [KoBeWi/Godot-Instance-Dock#6]
Allow the user to set export variable values for a scene in the dock.

Use case, i have a generic enemy scene which operates on resources for stats, visuals, etc... I'd like to be able to store enemy configurations in the dock instead of having to configure them every time i add an instance to the scene.

**Comment by KoBeWi** [comment]
That might be complicated to implement, but I'll see 🤔
In the meantime you can use inherited scenes.

**Comment by KoBeWi** [comment]
Implemented in d271a351ef6fa30b374707eb6b55c03b6c12f3f8

https://github.com/KoBeWi/Godot-Instance-Dock/assets/2223172/d0808e70-af1c-4ab4-8955-66c74d10177e
