### ISSUE TITLE
Reordering tabs not working

### ISSUE THREAD

**Issue by JUSTCAMH** [KoBeWi/Godot-Instance-Dock#8]
To replicate:
- Add two tabs, name them tab 1 and tab 2. Give them a few different scenes each
- Click and hold on tab 2, drag it left to the position of tab 1.
- The tab seems to have reordered correctly
- Re-select tab 2 (which is now in the position of tab 1)
- (BUG): Tab 2 shows the elements of tab 1, and selecting tab 1, this shows the elements of tab 2. When you reload the project, the tab order hasn't saved, it's in the same order as before

**Comment by KoBeWi** [comment]
Fixed in 533c133c56fc51c73a233a633f9961001e48a6bd
