### ISSUE TITLE
Add option to select default parent

### ISSUE THREAD

**Issue by JUSTCAMH** [KoBeWi/Godot-Instance-Dock#9]
This is an awesome asset, I just wanted to leave a feature request! My workflow involves both a tilemap and instances placed in the scene. In my world I've got a few little areas that I'm parenting these objects to for cleanliness in my scene hierarchy. The option to hold control to parent to the currently selected object is nice, but has a few flaws:
- To edit the tilemap, I've gotta be selecting the tilemap. So I can't simultaneously paint tiles and place objects in the scene.
- I am frequently selecting objects to edit some stuff on them, then need to switch back to selecting the parent to place more
- At any given time I have one parent that I want all placed objects to be parented to.

It would be helpful to have a default parent field that accepts any node in the current scene. I could drag and drop the intended parent into this field, then placing an instance would automatically assign it as a child of that node instead of scene root (while empty, would default to scene root). Holding Ctrl or Shift would override this behaviour. Something like below:
![image](https://github.com/KoBeWi/Godot-Instance-Dock/assets/43807990/8ea323b9-5367-4afc-b187-0002a4e076d4)

**Comment by KoBeWi** [comment]
This can't be implemented directly, because I just use Godot's default drag and drop function (it's the same as dragging scenes from FileSystem). When you drop, the node is under scene root. When you drop with Ctrl, the node is child of the selected node. If you drop with Shift, the node is sibling of the selected node.

However I plan to add a Painting Mode, where the default parent can be added.

**Comment by KoBeWi** [comment]
Implemented in 1ee16e32c92e2d1f7143b446b6bf4fc5dc1559a5
I realized I could actually add this feature for drag and drop too, but I didn't want the picker to take space, so for now it's only for paint mode. You can grab the newest version and check if it's fine like that (needs Godot 4.2+).

**Comment by JUSTCAMH** [comment]
I tried the paint mode, it took a while to figure out how to use, I didn't expect I'd need to be selecting an object in the hierarchy to use it (I guess this is a technical limitation?) and missed the text note telling what to do. Having documentation on the github readme would be handy!

Though I'm also finding the paint mode quite difficult to use now that I've figured it out. Firstly, this works poorly with tilemaps, I need to select the tilemap to place tiles but then need to select a canvas item to paint. I liked that with drag and drop, I could paint tiles, then seamlessly drag an object from the docker into the world (this would just parent it to the wrong thing, I tend to clean it up later). But also I find it clunky to go back and forth between painting and other forms of editing. When creating a world, I'm not just adding new objects, I'm also moving, rotating and scaling existing ones, deleting ones that are no good and trying to select other objects to edit them in the inspector. A keybind to toggle paint mode would be handy! And even more useful would be if paint mode were a tool in the toolbar above scene view, so I could press W to move some objects, then e.g. P to paint a few, then maybe E to rotate some stuff. But currently whilst paint mode is active all the other editing hotkeys (q, w, e, s, etc) are all ignored, which is breaking my flow.

As it stands, I feel paint mode is hindering more than helping, though I think it'd be handy with more usability tweaks. Also this might be more useful for other kinds of projects with more instances. It'd still be helpful to have a default parent option for the drag and drop controls, as paint mode and drag/drop can suit different workflows. Regardless, thanks for making the asset and keeping on top of feedback, it's been a big help building out my level so far!

**Comment by KoBeWi** [comment]
Ok 02f24f9f505e7f8c4c9cd49bb0e09bedb1fc4977 implements default parent for drag and drop. Dropping under default parent creates 2 undo actions; this is due to engine limitation.

I already planned to update the README, will do it sometime before official update.

**Comment by JUSTCAMH** [comment]
Thanks so much kobewi! I've been using that for a bit and noticed just one issue, when dragging and dropping directly into the scene hierarchy, the instance doesn't go where you placed, but instead to the parent selected. Same happens when holding control / shift, the object always gets parented to the selected parent. I believe the logic should be to only do the reparent step if the created object is parented directly to the scene tree; when parented to anything else, then the user must have selected a custom parent manually which should be respected.

**Comment by KoBeWi** [comment]
09f2a5a418af74c55914fed7f2a3b101b6fcec96

**Comment by JUSTCAMH** [comment]
Thanks!
